#!/usr/bin/env python3
import sys
import datetime
strptime=datetime.datetime.strptime

def is_dt_line(line):
    stamp = line.split('.')[0]
    try:
        dt=strptime(stamp,'%Y%m%dt%H%M%S')
        dT=strptime(stamp,'%Y%m%dT%H%M%S')
        return True
    except ValueError:
        return False
class BadLine(Exception):
    pass
def verify(path):
    with open(path) as fd:
        for ii,line in enumerate( fd.readlines() ):
            aa = line.split('.')[0]
            if not len(aa)==15:    raise BadLine(ii,line)
            if not is_dt_line(aa): raise BadLine(ii,line)
            if not aa[8]=='T':     raise BadLine(ii,line)
if __name__=='__main__':
    path = sys.argv[1]
    verify(path)
